export enum AdminActionType {
  CREATE_TEMPLATE = 'CREATE_TEMPLATE',
  UPDATE_TEMPLATE = 'UPDATE_TEMPLATE',
  ACTIVATE_TEMPLATE = 'ACTIVATE_TEMPLATE',
  DEACTIVATE_TEMPLATE = 'DEACTIVATE_TEMPLATE',
  CREATE_CLIENT_APP = 'CREATE_CLIENT_APP',
  UPDATE_CLIENT_APP = 'UPDATE_CLIENT_APP',
  BLOCK_CLIENT_APP = 'BLOCK_CLIENT_APP',
  CREATE_API_KEY = 'CREATE_API_KEY',
  REVOKE_API_KEY = 'REVOKE_API_KEY',
  GRANT_TEMPLATE_ACCESS = 'GRANT_TEMPLATE_ACCESS',
  REVOKE_TEMPLATE_ACCESS = 'REVOKE_TEMPLATE_ACCESS',
  RETRY_DISPATCH = 'RETRY_DISPATCH',
  CANCEL_DISPATCH = 'CANCEL_DISPATCH',
}

export enum AdminTargetType {
  TEMPLATE = 'TEMPLATE',
  TEMPLATE_CHANNEL = 'TEMPLATE_CHANNEL',
  MESSAGE_REQUEST = 'MESSAGE_REQUEST',
  MESSAGE_DISPATCH = 'MESSAGE_DISPATCH',
  CLIENT_APP = 'CLIENT_APP',
  API_KEY = 'API_KEY',
  CLIENT_TEMPLATE_ACCESS = 'CLIENT_TEMPLATE_ACCESS',
  CLIENT_CHANNEL_POLICY = 'CLIENT_CHANNEL_POLICY',
}
