export enum OutboxAggregateType {
  MESSAGE_REQUEST = 'MESSAGE_REQUEST',
  MESSAGE_DISPATCH = 'MESSAGE_DISPATCH',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}

export enum OutboxEventType {
  MESSAGE_REQUEST_CREATED = 'MESSAGE_REQUEST_CREATED',
  MESSAGE_REQUEST_CANCELED = 'MESSAGE_REQUEST_CANCELED',
  MESSAGE_DISPATCH_QUEUED = 'MESSAGE_DISPATCH_QUEUED',
  MESSAGE_DISPATCH_RETRY_SCHEDULED = 'MESSAGE_DISPATCH_RETRY_SCHEDULED',
  MESSAGE_DISPATCH_COMPLETED = 'MESSAGE_DISPATCH_COMPLETED',
  CHAT_MESSAGE_CREATED = 'CHAT_MESSAGE_CREATED',
}

export enum OutboxStatus {
  PENDING = 'PENDING',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
}
